---
- hosts: all
  gather_facts: no
  tasks:
    - name: Create fake config for testing
      copy:
        dest: /test_kubeconfig
        content: |
          apiVersion: v1
          kind: Config
          clusters:
          - name: remove_cluster
            cluster:
              server: https://localhost
          - name: keep_cluster
            cluster:
              server: https://localhost
          users:
          - name: remove_user
            user:
              username: fake
              password: sekrit
          - name: keep_user
            user:
              username: fake
              password: sekrit
          contexts:
          - name: remove_context
            context:
              user: remove_user
              cluster: remove_cluster
